

namesMora <- c("FECHAPROC", "ID_CONTRATO", "FECHA_PAGO", "DEUDA_INICIAL", "EN_MORA",
               "DIAS", "ESTADO_PAGO", "ESTRATEGIA_RECOBRO", "RIESGO", "DIVISA", "SALDO_CAPITAL", "SALDO_INTERESES_CAPITAL",
               "SALDO_INTERESES_MORA", "LINEACREDITO", "LINEA", "YEAR_MONTH")

productsToIncludeMora <- c("TARJETA_DE_CREDITO_EXPRESS", "TARJETA_DE_CREDITO_CREDIBANCO")

colsToSelectMora <- c("ID_CONTRATO", "FECHA_PAGO", "DEUDA_INICIAL", "EN_MORA",
                      "DIAS","ESTRATEGIA_RECOBRO", "RIESGO", "SALDO_CAPITAL", "SALDO_INTERESES_CAPITAL",
                      "SALDO_INTERESES_MORA", "LINEACREDITO", "LINEA","YEAR_MONTH", "YEAR_MONTH_DAY")

numColsMora <- c("DIAS", "EN_MORA", "SALDO_CAPITAL", "FECHA_PAGO",
                 "LINEACREDITO", "DEUDA_INICIAL", "SALDO_INTERESES_CAPITAL",
                 "SALDO_INTERESES_MORA")

numColsContratos <- c("BRANCH_DEL_CONTRATO", "BRANCH_DEL_CLIENTE","DEUDA_TOTAL_INICIAL", "SAL_CAPITA", "VLR_CUOTA")
dateColsContratos <- c("FECHA_DE_FINALIZACION", "FECHA_DE_INICIO")


binomColsContratos <- c("REFINANCIADO", "CONTRATO_EN_MORA" )

colsToSelectContratos <- c("ID_CLIENTE",
                           "ID_CONTRATO",
                           "BRANCH_DEL_CONTRATO",
                           "BRANCH_DEL_CLIENTE",
                           "FECHA_DE_INICIO",
                           "FECHA_DE_FINALIZACION",
                           "CONTRATO_EN_MORA",
                           "TIPO_DE_PRODUCTO",
                           "REFINANCIADO",
                           "DEUDA_TOTAL_INICIAL",
                           "SAL_CAPITA",
                           "VLR_CUOTA",
                           "YEAR_MONTH")
numColsTx_pasivo <- c("VALOR_TX")


namesBuro <- c("ID_CLIENTE",
               "RANGO_APROXIMADO_EDAD",
               "GENERO",
               "CIUDAD_EXPEDICION",
               "NUM_OBLIG_ACTIV",
               "NUM_CREDITOS_CB",
               "VALOR_INICIAL_CB",
               "VALOR_SALDO_CB",
               "VALOR_CUOTAS_CB",
               "VALOR_MORA_CB",
               "NUM_CREDITOS_CV",
               "VALOR_INICIAL_CV", 
               "VALOR_SALDO_CV",
               "VALOR_CUOTAS_CV",
               "VALOR_MORA_CV",
               "NUM_CREDITOS_OCF",
               "VALOR_INICIAL_OCF",
               "VALOR_SALDO_OCF",
               "VALOR_CUOTAS_OCF", 
               "VALOR_MORA_OCF",
               "NUM_TDC",
               "VALOR_CUPOS_TDC",
               "VALOR_UTILIZADO_TDC", 
               "PORC_UTILIZACION_TDC", 
               "VALOR_CUOTAS_TDC",
               "VALOR_MORA_TDC", 
               "FECHA_MAS_ANTIGUA_TDC",
               "NUM_CREDITOS_SR", 
               "VALOR_INICIAL_SR", 
               "VALOR_SALDO_SR",
               "VALOR_CUOTAS_SR", 
               "VALOR_MORA_SR",
               "NUM_CELULARES_TELCOS",
               "VALOR_CUOTAS_CELULARES_TELCOS",
               "VALOR_MORA_TELCOS",
               "NUM_CREDITOS_COOP",
               "VALOR_INICIAL_COOP",
               "VALOR_SALDO_COOP",
               "VALOR_CUOTAS_COOP",
               "VALOR_MORA_COOP",
               "NUM_CREDITOS_COD",
               "VALOR_SALDO_COD",
               "VALOR_CUOTAS_COD",
               "VALOR_MORA_COD",
               "NUM_OBLIG_AL_DIA",
               "OBLIG_MORA_30",
               "OBLIG_MORA_60",
               "OBLIG_MORA_90",
               "OBLIG_MORA_120",
               "CARTERA_CASTIGADA",
               "DUDOSO_RECAUDO",
               "CUENTAS_EN_COBRADOR",
               "NUM_MORAS_30_365",
               "NUM_MORAS_60_365",
               "NUM_MORAS_90_365",
               "NUM_MORAS_120_365",
               "NUM_CANCELADAS_MAL_MANEJO_365",
               "NUM_CARTERA_RECUPERADA_365",
               "ALTURA_MAX_MORA_TDC",
               "ALTURA_MAX_MORA_CB",
               "ALTURA_MAX_MORA_COOP",
               "ALTURA_MAX_MORA_CV",
               "PEOR_CALIFICACION_T1",
               "PEOR_CALIFICACION_T2",
               "CUENTAS_DE_AHORRO_ACTIVAS",
               "CUENTAS_CORRIENTES_ACTIVAS",
               "CUENTAS_EMBARGADAS",
               "CANCELADAS_MAL_MANEJO",
               "CUENTAS_SALDADAS",
               "TOTAL_CONSULTAS_ULTIMOS_6_MESES",
               "ESTADO_CONSULTA",
               "ACIERTA_A_FINANCIERO",
               "QUANTO3",
               "YEAR_MONTH")	

numericColumnsBuro <- c("NUM_OBLIG_ACTIV",
                        "NUM_CREDITOS_CB",
                        "VALOR_INICIAL_CB",
                        "VALOR_SALDO_CB",
                        "VALOR_CUOTAS_CB",
                        "VALOR_MORA_CB",
                        "NUM_CREDITOS_CV",
                        "VALOR_INICIAL_CV", 
                        "VALOR_SALDO_CV",
                        "VALOR_CUOTAS_CV",
                        "VALOR_MORA_CV",
                        "NUM_CREDITOS_OCF",
                        "VALOR_INICIAL_OCF",
                        "VALOR_SALDO_OCF",
                        "VALOR_CUOTAS_OCF", 
                        "VALOR_MORA_OCF",
                        "NUM_TDC",
                        "VALOR_CUPOS_TDC",
                        "VALOR_UTILIZADO_TDC", 
                        "PORC_UTILIZACION_TDC", 
                        "VALOR_CUOTAS_TDC",
                        "VALOR_MORA_TDC", 
                        "NUM_CREDITOS_SR", 
                        "VALOR_INICIAL_SR", 
                        "VALOR_SALDO_SR",
                        "VALOR_CUOTAS_SR", 
                        "VALOR_MORA_SR",
                        "NUM_CELULARES_TELCOS",
                        "VALOR_CUOTAS_CELULARES_TELCOS",
                        "VALOR_MORA_TELCOS",
                        "NUM_CREDITOS_COOP",
                        "VALOR_INICIAL_COOP",
                        "VALOR_SALDO_COOP",
                        "VALOR_CUOTAS_COOP",
                        "VALOR_MORA_COOP",
                        "NUM_CREDITOS_COD",
                        "VALOR_SALDO_COD",
                        "VALOR_CUOTAS_COD",
                        "VALOR_MORA_COD",
                        "NUM_OBLIG_AL_DIA",
                        "OBLIG_MORA_30",
                        "OBLIG_MORA_60",
                        "OBLIG_MORA_90",
                        "OBLIG_MORA_120",
                        "CARTERA_CASTIGADA",
                        "DUDOSO_RECAUDO",
                        "CUENTAS_EN_COBRADOR",
                        "NUM_MORAS_30_365",
                        "NUM_MORAS_60_365",
                        "NUM_MORAS_90_365",
                        "NUM_MORAS_120_365",
                        "NUM_CANCELADAS_MAL_MANEJO_365",
                        "NUM_CARTERA_RECUPERADA_365",
                        "ALTURA_MAX_MORA_TDC",
                        "ALTURA_MAX_MORA_CB",
                        "ALTURA_MAX_MORA_COOP",
                        "ALTURA_MAX_MORA_CV",
                        "CUENTAS_DE_AHORRO_ACTIVAS",
                        "CUENTAS_CORRIENTES_ACTIVAS",
                        "CUENTAS_EMBARGADAS",
                        "CANCELADAS_MAL_MANEJO",
                        "CUENTAS_SALDADAS",
                        "TOTAL_CONSULTAS_ULTIMOS_6_MESES",
                        "ESTADO_CONSULTA",
                        "ACIERTA_A_FINANCIERO",
                        "QUANTO3")	

listaEntidadesAval <- c("BCO AVVILLAS",
                        "BCO DE BOGOTA",
                        "BCO POPULAR",
                        "CTEOCCIDENTE",
                        "LEASING CORFICOLOMBIAN",
                        "COOPORVENIR")

varsToSelectClientes <- c("AA_NIT_ENCRIPTADO", 
                          "GENERO",
                          "FECHA_NACIMIENTO",
                          "YEAR_MONTH"
                          )

fechasMasterTable <- c("FECHA_DE_INICIO_CONT",
                       "FECHA_DE_FINALIZACION_CONT",
                       "FECHA_MAS_ANTIGUA_TDC_BURO")
